### ISSUE TITLE
v1.2.1 generates incorrect code for enum type (missing leading character)

### ISSUE THREAD

**Issue by meling** [grpc/grpc-web#1039]
Upgrading from v1.2.0 to v1.2.1 results in non-compilable code in `_pb.d.ts`.

The following (minimized) proto file compiles fine with v1.2.0:
```proto
syntax = "proto3";

message Group {
    enum GroupStatus {
        PENDING = 0;
        APPROVED = 1;
    }
    uint64 ID = 1;
    GroupStatus status = 2;
}
```
The generated code looks like this:
```typescript
...
  getStatus(): roup.GroupStatus;
  setStatus(value: roup.GroupStatus): Group;
...
export namespace Group {
  export type AsObject = {
    id: number,
    status: roup.GroupStatus,
  }

  export enum GroupStatus { 
    PENDING = 0,
    APPROVED = 1,
  }
}
```
As can be seen, references to the encapsulated enum type `roup.GroupStatus` should be `Group.GroupStatus`. A similar problem happens if the enum type is moved outside the `Group` message:
```typescript
export namespace Group {
  export type AsObject = {
    id: number,
    status: roupStatus,
  }
}

export enum GroupStatus { 
  PENDING = 0,
  APPROVED = 1,
}
```

Command used to compile (works fine with v1.2.0):
```console
% protoc -I=. -I=$(pbpath) \
	--js_out=import_style=commonjs:../$(proto-path)/ \
	--grpc-web_out=import_style=typescript,mode=grpcweb:../$(proto-path)/ ag.proto
```

This results in compile errors similar to this (included for people searching for this error message):
```console
proto/ag_pb.d.ts:9:16 - error TS2503: Cannot find namespace 'roup'.

9   getStatus(): roup.GroupStatus;
                 ~~~~
```

**Comment by stanley-cheung** [comment]
Will need to look into this.

**Comment by stanley-cheung** [comment]
Looks like this has been fixed by #941. I ran the code generator plugin on HEAD and the above .proto generates fine.

**Comment by sampajano** [comment]
We should do a release fairly soon! Stay tuned.. :)

Please follow https://github.com/grpc/grpc-web/issues/1043 in the meanwhile. :)

**Comment by caesuric** [comment]
> We should cut a release fairly soon! Stay tuned.. :)
> 
> Please follow #1043 in the meanwhile. :)

This is great news, thank you! I'll stay tuned. ;)

**Comment by sampajano** [comment]
We've just cut the 1.3.0 release:
https://github.com/grpc/grpc-web/releases/tag/1.3.0

Hope this issue is fixed now!

@caesuric FYI :)

**Comment by caesuric** [comment]
Hurray! I will check this out as soon as I am able. Thank you!
